version: '3'
services:
  database:
    build: docker/database
    ports:
      - $DATABASE_PORT
    volumes:
      - database:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: database
      POSTGRES_PASSWORD: database
  mailcatcher:
    image: tophfr/mailcatcher
    ports:
      - $MAILCATCHER_PORT
      - 25
  php:
    build: docker/php-fpm
    volumes:
      - ./code:/var/www/app
      - ./docker/php-fpm/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - database
  nginx:
    image: nginx:latest
    ports:
      - $NGINX_PORT
    volumes:
      - ./code:/var/www/app
      - ./docker/nginx/app.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
volumes:
  database: